name: hmssdk_flutter
description: The official Flutter Plugin for 100ms SDK
version: 0.0.1
homepage: https://www.100ms.live/
repository: https://github.com/100mslive/100ms-flutter
issue_tracker: https://github.com/100mslive/100ms-flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: live.hms.hmssdk_flutter
        pluginClass: HmssdkFlutterPlugin
      ios:
        pluginClass: HmssdkFlutterPlugin